### PR TITLE
feat: added parse semester events function

### LINKED ISSUE #4: Dynamically updating semester event data
currently the semester events data is hard coded in [data.ts](https://github.com/nur-zaman/better-usis/blob/master/constants/data.ts)
need to make it dynamic by using [https://www.bracu.ac.bd/academic/spring/2023/rss.xml](https://www.bracu.ac.bd/academic/spring/2023/rss.xml) .

### PR DESCRIPTION
**Pull request by NaiveInvestigator**
I am almost done with this PR, but kinda stuck on how to make betterusis use the parsed data. But otherwise it seems to work :>>

Also i have not added anything that will decide what semester it is currently, and will request the xml accordingly.
Fixes #4.

### CODE REVIEW

**Comment by nur-zaman** [comment]
Thank you.
Do you wanna try adding it overview tab ( `components\tabs\overview-tab.tsx`  )? or should I just merge it .

Also, please make the format same as the previous one. from `constants\data.ts`,
```
{
  "from_date": "2024-04-08",
  "to_date": "2024-04-13",
  "day": "Monday to Saturday",
  "title": "Eid-ul-Fitr-University closed"
},
```

**Comment by NaiveInvestigator** [comment]
> Thank you. Do you wanna try adding it overview tab ( `components\tabs\overview-tab.tsx` )? or should I just merge it .

For now i'll try to figure it out, if I cant i'll let u know and then merge. Hope it doesnt take more weeks :skull: 

> Also, please make the format same as the previous one. from `constants\data.ts`,
> 
> ```
> {
>   "from_date": "2024-04-08",
>   "to_date": "2024-04-13",
>   "day": "Monday to Saturday",
>   "title": "Eid-ul-Fitr-University closed"
> },
> ```
Oh mb i didnt notice that, will fix it up :>

**Comment by nur-zaman** [comment]
Hi,
Can you please let me know if are you still working on it?
if not then I'll merge the functioning part from the pull request and then make necessary modifications

**Comment by NaiveInvestigator** [comment]
sorry for holding up :< 

i think you should just merge whatever you need. I am a bit busy so I couldn't find time to fix up those issues.

Very sorry for the inconvenience.

**Comment by nur-zaman** [comment]
Okay. I'll do that 😄

**Pull request closed without merging**
